[UnrealEd.SimpleMap]
; 与 DefaultEngine 使用同一引擎模板关（无项目 Content 时）
SimpleMapName=/Engine/Maps/Templates/Template_Default.Template_Default

[EditoronlyBP]
bAllowClassAndBlueprintPinMatching=true
bReplaceBlueprintWithClass=true
bDontLoadBlueprintOutsideEditor= true
bBlueprintIsNotBlueprintType= true

